{
 "title": "Jenkins",
 "tags": [
  "consul.builds",
  "jenkins",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "_host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"jvm_memory\" WITH KEY = \"host\" WHERE \"category\"=~/build.*/"
   },
   {
    "name": "_role",
    "label": "Role",
    "query": "SHOW TAG VALUES FROM \"jvm_memory\" WITH KEY = \"category\" WHERE \"category\"=~/build.*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue vs Executors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "alias": "Queue ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_queue",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Size" }
     ]
    },
    {
     "alias": "Executors - In-use ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_executor",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "In-use" }
     ]
    }
   ]
  },
  {
   "title": "Executor - Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_executor",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Free" }
     ]
    }
   ]
  },
  {
   "title": "Nodes - Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_node",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Online" }
     ]
    }
   ]
  },
  {
   "title": "Executor - In use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_executor",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "In-use" }
     ]
    }
   ]
  },
  {
   "title": "Nodes - Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_node",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Offline" }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_queue",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Plugins - Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_plugins",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Active" }
     ]
    }
   ]
  },
  {
   "title": "Plugins - Inactive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_plugins",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Inactive" }
     ]
    }
   ]
  },
  {
   "title": "Plugins - Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_plugins",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "WithUpdate" }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Consumers",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "jenkins.trigger" }
     ]
    }
   ]
  },
  {
   "title": "Enabled projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_project",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Enabled" }
     ]
    }
   ]
  },
  {
   "title": "Disabled projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_project",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Disabled" }
     ]
    }
   ]
  },
  {
   "title": "Plugins - Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_plugins",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Failed" }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_web_requests",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "$tag_name ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_web_requests_active",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Host - Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "% Utilization" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\" =~ /^$_environment$/ AND \"category\" =~ /^$_role$/ AND \"os\" = 'windows') AND $timeFilter GROUP BY time($_bucket), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Cpu (guest)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (iowait)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (system)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (user)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_web_reponsecodes",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Host - Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Memory free" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Max ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - % Heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit", "label": "Heap Utilization" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "query": "SELECT MAX( \"utilization\") FROM ( SELECT \"HeapMemoryUsage.used\" / \"HeapMemoryUsage.max\" AS \"utilization\" FROM \"jvm_memory\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\" =~ /^$_environment$/ AND \"category\" =~ /^$_role$/) AND $timeFilter) GROUP BY time($_bucket), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapMemoryUsage.used" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Collections / s" }
   ],
   "targets": [
    {
     "alias": "Count ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Pending finalize ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "ObjectPendingFinalizationCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Collection committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Collection used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Peak committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Peak used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Usage committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Usage used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM non-Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Init ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  }
 ]
}