{
 "title": "Reverse proxy",
 "tags": [
  "service",
  "consul.proxy"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "_bucket", "label": "Bucket", "query": "1m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "50-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "75-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "95-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "99-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "99.9%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "999-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "100%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    }
   ]
  },
  {
   "title": "Installers - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    }
   ]
  },
  {
   "title": "Installers - Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_50-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_75-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_95-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_99-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "99.9%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_999-percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    },
    {
     "alias": "100%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "__/artefacts/installers_172_17_26_60_80_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "fabio" }
     ]
    }
   ]
  }
 ]
}