{
 "title": "InfluxDb",
 "tags": [
  "consul.metrics",
  "influxdb",
  "meta",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "InfluxDB size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_shard",
     "query": "SELECT sum(\"diskBytes\") FROM \"influxdb_shard\" WHERE \"category\" = 'metrics-storage' AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points Written",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No.  Measurements",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "No. Series",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_shard",
     "query": "SELECT sum(\"diskBytes\") FROM \"influxdb_shard\" WHERE \"category\" = 'metrics-storage' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    },
    {
     "alias": "Cache (disk)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_tsm1_wal",
     "query": "SELECT sum(\"diskBytes\") FROM \"influxdb_shard\" WHERE \"category\" = 'metrics-storage' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "currentSegmentDiskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influxdb_shard",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Queries",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Client Error",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Server Error",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements/Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Series",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    },
    {
     "alias": "Measurements",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenOK" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Influx",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_runtime",
     "select": [
      [
       { "params": [ "Sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    },
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "metrics-storage" }
     ]
    }
   ]
  }
 ]
}