{
 "title": "Vault Cluster Health",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_host",
    "label": "Host",
    "query": "show tag values with key = \"host\" where category = 'secrets'"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "show tag values with key = \"environment\" where category = 'secrets'"
   }
  ]
 },
 "panels": [
  {
   "title": "Seal Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_host" ], "type": "tag" },
      { "params": [ "service_name" ], "type": "tag" }
     ],
     "measurement": "consul_health_checks",
     "query": "SELECT last(\"passing\") AS unsealed FROM \"consul_health_checks\" WHERE category='secrets' AND check_name='Vault Sealed Status' GROUP BY \"check_id\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_user\") AS \"user_cpu\", max(\"usage_iowait\") AS \"iowait_cpu\" FROM \"cpu\" WHERE (\"category\"='secrets' AND \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "secrets" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_difference(max(\"read_bytes\")) + non_negative_difference(max(\"write_bytes\")) AS \"bytes\" FROM \"diskio\" WHERE (\"category\"='secrets' AND \"host\" =~ /^$_host$/ AND \"environment\"  =~ /^$_environment$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "servicehub" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_difference(max(\"bytes_recv\")) + non_negative_difference(max(\"bytes_sent\")) AS \"bytes\" FROM \"net\" WHERE (\"category\"='secrets' AND \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "servicehub" }
     ]
    }
   ]
  },
  {
   "title": "Request Handle Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "core_handle_request",
     "query": "SELECT mean(\"value\") AS \"count\" FROM \"core_handle_request\" WHERE $timeFilter AND \"category\"='servicehub' GROUP BY time($__interval), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.alloc_bytes",
     "query": "SELECT max(\"value\") AS \"alloc_bytes\" FROM \"vault.runtime.alloc_bytes\" WHERE (\"category\"='secrets' AND \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "secrets" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"sys_bytes\" FROM \"vault.runtime.sys_bytes\" WHERE (\"category\"='secrets' AND \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") AS \"total_bytes\" FROM \"mem\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/ AND \"category\"='secrets') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "secrets" }
     ]
    }
   ]
  },
  {
   "title": "Consul GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.get",
     "query": "SELECT mean(\"90_percentile\") AS \"90_percentile\" FROM \"vault.consul.get\" WHERE \"environment\"=~/^$_environment$/ AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.get",
     "query": "SELECT mean(\"mean\") FROM \"vault.consul.get\" WHERE \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consul PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.put",
     "query": "SELECT mean(\"90_percentile\") AS \"90_percentile\" FROM \"vault.consul.put\" WHERE \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.put",
     "query": "SELECT mean(\"mean\") FROM \"vault.consul.put\" WHERE \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Persist Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.wal.persistWALs",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.gc_pause_ns",
     "query": "SELECT last(\"upper\")/1000000 AS \"milliseconds\" FROM \"vault.runtime.gc_pause_ns\" WHERE $timeFilter AND \"category\"='secrets' GROUP BY host, time($__interval) FILL(0)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "secrets" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Consul LIST",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.list",
     "query": "SELECT mean(\"90_percentile\") AS \"90_percentile\" FROM \"vault.consul.list\" WHERE \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.list",
     "query": "SELECT mean(\"mean\") FROM \"vault.consul.list\" WHERE \"host\" =~ /^$_host$/ AND \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consul DELETE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.delete",
     "query": "SELECT mean(\"90_percentile\") AS \"90_percentile\" FROM \"vault.consul.delete\" WHERE \"environment\"=~/^$_environment$/  AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.consul.delete",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "WAL Flush Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.wal.flushReady",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Leadership Loss",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 15 },
   "format": "ms",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.core.leadership_lost",
     "query": "SELECT max(\"upper\") FROM \"vault.core.leadership_lost\" WHERE (\"environment\"=~/^$_environment$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}