{
 "title": "Jenkins",
 "tags": [
  "service",
  "consul.build"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "_host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"jvm_memory\" WITH KEY = \"host\""
   },
   {
    "name": "_role",
    "label": "Role",
    "query": "SHOW TAG VALUES FROM \"jvm_memory\" WITH KEY = \"build\""
   }
  ]
 },
 "panels": [
  {
   "title": "Jenkins - Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Collections / s" }
   ],
   "targets": [
    {
     "alias": "Count ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Pending finalize ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "ObjectPendingFinalizationCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Host - Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "% Utilization" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\" =~ /^$_environment$/ AND \"build\" =~ /^$_role$/) AND $timeFilter GROUP BY time($_bucket), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Host - Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory free" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit", "label": "Cpu Load" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_vm_cpu",
     "query": "SELECT mean(\"Value\") FROM \"jenkins_vm_cpu\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\" =~ /^$_environment$/ AND \"build\" =~ /^$_role$/) AND $timeFilter GROUP BY time($_bucket), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins -  Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Memory used" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_vm_memory",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Max ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - % Heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "Heap Utilization" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "query": "SELECT MAX( \"utilization\") FROM ( SELECT \"HeapMemoryUsage.used\" / \"HeapMemoryUsage.max\" AS \"utilization\" FROM \"jvm_memory\" WHERE (\"host\" =~ /^$_host$/ AND \"environment\" =~ /^$_environment$/ AND \"build\" =~ /^$_role$/) AND $timeFilter) GROUP BY time($_bucket), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapMemoryUsage.used" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM non-Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Init ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Collection committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Collection used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Peak committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Peak used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Usage committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Usage used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins nodes & executors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Executors ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_executor",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Nodes ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_node",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Web",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Requests ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_web_requests",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Response codes ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_web_reponsecodes",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  },
  {
   "title": "Jenkins - Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Jobs ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_job_scheduled",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    },
    {
     "alias": "Queue ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jenkins_queue",
     "select": [
      [
       { "params": [ "Value.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "build", "operator": "=~", "value": "/^$_role$/" }
     ]
    }
   ]
  }
 ]
}