{
 "title": "Single host (telegraf)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "_host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk space free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Space Free" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "$tag_path ($tag_device)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT 100 - mean(\"used_percent\") FROM \"disk\" WHERE (\"host\" =~ /^$_host$/ AND \"os\" = 'linux') AND $timeFilter GROUP BY time($_bucket), \"instance\", \"device\", \"path\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Data Written" }
   ],
   "targets": [
    {
     "alias": "Write $tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Mem / CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Free" }
   ],
   "targets": [
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "objectname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"host\" =~ /^$_host$/ AND \"os\" = 'windows') AND $timeFilter GROUP BY time($_bucket), \"objectname\" fill(null)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "Cpu",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$_host$/ AND \"instance\" = '_Total' AND \"os\" = 'windows') AND $timeFilter GROUP BY time($_bucket) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    },
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (guest)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (iowait)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (system)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    },
    {
     "alias": "Cpu (user)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Data Read" }
   ],
   "targets": [
    {
     "alias": "Read $tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops", "label": "Context Switches" }
   ],
   "targets": [
    {
     "alias": "Switches",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Context_Switches_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Network Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Written" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  },
  {
   "title": "Network Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Received" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "windows" }
     ]
    },
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "linux" }
     ]
    }
   ]
  }
 ]
}