{
 "title": "Hyper-V",
 "tags": [
  "infrastructure",
  "hypervisor",
  "physical"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "15s, 1m, 5m, 10m, 30m, 1h, 1d, 7d"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "_host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Hypervisor use",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "hyper_v_hypervisor",
     "select": [
      [
       { "params": [ "Logical_Processors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Logical processors" ], "type": "alias" }
      ],
      [
       { "params": [ "Virtual_Processors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Virtual processors" ], "type": "alias" }
      ],
      [
       { "params": [ "Partitions" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Active virtual machines" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_dynamic_memory_balancer",
     "select": [
      [
       { "params": [ "Available_Memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hyper_v_dynamic_memory_balancer",
     "select": [
      [
       { "params": [ "Average_Pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total CPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% Guest run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_logical_processor",
     "select": [
      [
       { "params": [ "Percent_Guest_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "% Hypervisor run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_logical_processor",
     "select": [
      [
       { "params": [ "Percent_Hypervisor_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "% Total run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_logical_processor",
     "select": [
      [
       { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% Guest run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_root_virtual_processor",
     "select": [
      [
       { "params": [ "Percent_Guest_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "% Hypervisor run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_root_virtual_processor",
     "select": [
      [
       { "params": [ "Percent_Hypervisor_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "% Total run time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_hypervisor_root_virtual_processor",
     "select": [
      [
       { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Disk read / s ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Disk write / s ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Builds",
   "type": "graph",
   "description": "Note: This is not the correct data to display. In reality we only care about those builds executed on one of the hyper-v hosts and ideally we would be able to figure out which VM runs on which host",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "builds.build.completed",
     "select": [
      [
       { "params": [ "executing" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "Total ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Packets_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Received ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Packets_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Broadcast received ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       {
        "params": [
         "Broadcast_Packets_Received_persec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Broadcast send ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Broadcast_Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Directed received ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       {
        "params": [
         "Directed_Packets_Received_persec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Total ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Received ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Send ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hyper_v_virtual_switch",
     "select": [
      [
       { "params": [ "Bytes_Send_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    }
   ]
  }
 ]
}